/* Generated by Cython 0.23.1 */

#ifndef __PYX_HAVE__equations__solar_system__solar_system_derivative
#define __PYX_HAVE__equations__solar_system__solar_system_derivative


#ifndef __PYX_HAVE_API__equations__solar_system__solar_system_derivative

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(double) m_sun;
__PYX_EXTERN_C DL_IMPORT(double) m_mercury;
__PYX_EXTERN_C DL_IMPORT(double) m_venus;
__PYX_EXTERN_C DL_IMPORT(double) m_earth;
__PYX_EXTERN_C DL_IMPORT(double) m_mars;
__PYX_EXTERN_C DL_IMPORT(double) m_jupiter;
__PYX_EXTERN_C DL_IMPORT(double) m_saturn;
__PYX_EXTERN_C DL_IMPORT(double) m_uranus;
__PYX_EXTERN_C DL_IMPORT(double) m_neptune;
__PYX_EXTERN_C DL_IMPORT(double) m_pluto;
__PYX_EXTERN_C DL_IMPORT(double) x_sun;
__PYX_EXTERN_C DL_IMPORT(double) x_mercury;
__PYX_EXTERN_C DL_IMPORT(double) x_venus;
__PYX_EXTERN_C DL_IMPORT(double) x_earth;
__PYX_EXTERN_C DL_IMPORT(double) x_mars;
__PYX_EXTERN_C DL_IMPORT(double) x_jupiter;
__PYX_EXTERN_C DL_IMPORT(double) x_saturn;
__PYX_EXTERN_C DL_IMPORT(double) x_uranus;
__PYX_EXTERN_C DL_IMPORT(double) x_neptune;
__PYX_EXTERN_C DL_IMPORT(double) x_pluto;
__PYX_EXTERN_C DL_IMPORT(double) y_sun;
__PYX_EXTERN_C DL_IMPORT(double) y_mercury;
__PYX_EXTERN_C DL_IMPORT(double) y_venus;
__PYX_EXTERN_C DL_IMPORT(double) y_earth;
__PYX_EXTERN_C DL_IMPORT(double) y_mars;
__PYX_EXTERN_C DL_IMPORT(double) y_jupiter;
__PYX_EXTERN_C DL_IMPORT(double) y_saturn;
__PYX_EXTERN_C DL_IMPORT(double) y_uranus;
__PYX_EXTERN_C DL_IMPORT(double) y_neptune;
__PYX_EXTERN_C DL_IMPORT(double) y_pluto;
__PYX_EXTERN_C DL_IMPORT(double) z_sun;
__PYX_EXTERN_C DL_IMPORT(double) z_mercury;
__PYX_EXTERN_C DL_IMPORT(double) z_venus;
__PYX_EXTERN_C DL_IMPORT(double) z_earth;
__PYX_EXTERN_C DL_IMPORT(double) z_mars;
__PYX_EXTERN_C DL_IMPORT(double) z_jupiter;
__PYX_EXTERN_C DL_IMPORT(double) z_saturn;
__PYX_EXTERN_C DL_IMPORT(double) z_uranus;
__PYX_EXTERN_C DL_IMPORT(double) z_neptune;
__PYX_EXTERN_C DL_IMPORT(double) z_pluto;
__PYX_EXTERN_C DL_IMPORT(double) vx_sun;
__PYX_EXTERN_C DL_IMPORT(double) vx_mercury;
__PYX_EXTERN_C DL_IMPORT(double) vx_venus;
__PYX_EXTERN_C DL_IMPORT(double) vx_earth;
__PYX_EXTERN_C DL_IMPORT(double) vx_mars;
__PYX_EXTERN_C DL_IMPORT(double) vx_jupiter;
__PYX_EXTERN_C DL_IMPORT(double) vx_saturn;
__PYX_EXTERN_C DL_IMPORT(double) vx_uranus;
__PYX_EXTERN_C DL_IMPORT(double) vx_neptune;
__PYX_EXTERN_C DL_IMPORT(double) vx_pluto;
__PYX_EXTERN_C DL_IMPORT(double) vy_sun;
__PYX_EXTERN_C DL_IMPORT(double) vy_mercury;
__PYX_EXTERN_C DL_IMPORT(double) vy_venus;
__PYX_EXTERN_C DL_IMPORT(double) vy_earth;
__PYX_EXTERN_C DL_IMPORT(double) vy_mars;
__PYX_EXTERN_C DL_IMPORT(double) vy_jupiter;
__PYX_EXTERN_C DL_IMPORT(double) vy_saturn;
__PYX_EXTERN_C DL_IMPORT(double) vy_uranus;
__PYX_EXTERN_C DL_IMPORT(double) vy_neptune;
__PYX_EXTERN_C DL_IMPORT(double) vy_pluto;
__PYX_EXTERN_C DL_IMPORT(double) vz_sun;
__PYX_EXTERN_C DL_IMPORT(double) vz_mercury;
__PYX_EXTERN_C DL_IMPORT(double) vz_venus;
__PYX_EXTERN_C DL_IMPORT(double) vz_earth;
__PYX_EXTERN_C DL_IMPORT(double) vz_mars;
__PYX_EXTERN_C DL_IMPORT(double) vz_jupiter;
__PYX_EXTERN_C DL_IMPORT(double) vz_saturn;
__PYX_EXTERN_C DL_IMPORT(double) vz_uranus;
__PYX_EXTERN_C DL_IMPORT(double) vz_neptune;
__PYX_EXTERN_C DL_IMPORT(double) vz_pluto;
__PYX_EXTERN_C DL_IMPORT(double) ti;
__PYX_EXTERN_C DL_IMPORT(double) years;
__PYX_EXTERN_C DL_IMPORT(double) days_per_year;
__PYX_EXTERN_C DL_IMPORT(double) hours_per_day;
__PYX_EXTERN_C DL_IMPORT(double) seconds_per_hour;
__PYX_EXTERN_C DL_IMPORT(double) tf;
__PYX_EXTERN_C DL_IMPORT(double) time_interval;
__PYX_EXTERN_C DL_IMPORT(double) dt;
__PYX_EXTERN_C DL_IMPORT(double) G;
__PYX_EXTERN_C DL_IMPORT(int) number_dimensions;

#endif /* !__PYX_HAVE_API__equations__solar_system__solar_system_derivative */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initsolar_system_derivative(void);
#else
PyMODINIT_FUNC PyInit_solar_system_derivative(void);
#endif

#endif /* !__PYX_HAVE__equations__solar_system__solar_system_derivative */
